// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valhaus.Data.Data;

#nullable disable

namespace Valhaus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Valhaus.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Tables"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sofas"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("Valhaus.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Low-profile oak coffee table with rounded corners — minimalist Scandinavian design.",
                            ListPrice = 499.0,
                            Price = 449.0,
                            Price100 = 349.0,
                            Price50 = 399.0,
                            SKU = "VH-CT-001",
                            Title = "Oslo Coffee Table"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Hand-glazed ceramic vase in matte white — understated elegance.",
                            ListPrice = 59.990000000000002,
                            Price = 49.990000000000002,
                            Price100 = 29.989999999999998,
                            Price50 = 39.990000000000002,
                            SKU = "VH-VS-001",
                            Title = "Nordic Ceramic Vase - Small"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Corner modular sofa with low profile and wooden base — configurable layout.",
                            ListPrice = 3299.0,
                            Price = 2999.0,
                            Price100 = 2399.0,
                            Price50 = 2699.0,
                            SKU = "VH-SF-002",
                            Title = "Nord Modular Sofa - Corner"
                        });
                });

            modelBuilder.Entity("Valhaus.Models.Models.Product", b =>
                {
                    b.HasOne("Valhaus.Models.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
